### ISSUE TITLE
音の選曲

### ISSUE THREAD

**Issue by nakachan0227** [TakezawaShuma/GraduationProduction#107]
>BGM

>足音

等の音を捜索・収集

きちんとゲームの雰囲気に合ったものを収集してくる

**Comment by nakachan0227** [comment]
->BGM

->足音

に加えて

->海の音

->川の音

->SE(斬撃・打撃・倒れた時・攻撃を受けた時)

も収集しました。

**Comment by TakezawaShuma** [comment]
選曲した候補が
> 一時フォルダ￥GT_12_中川

にあるそうなので使いたい音を挙げてください。

**Comment by Margin76** [comment]
MMOSound選曲に選んだ曲入ってます。
