### ISSUE TITLE
当たり判定

### ISSUE THREAD

**Issue by NakagawaTenmaa** [TakezawaShuma/GraduationProduction#79]
Unityのエディター上では正しく動くのですが
ビルド後のEXEで実行すると敵との判定処理が動きません

上記の解決策としてもうコライダーを使った当たり判定ではなく
距離の計算で判定してみるといいかも

**Comment by TakezawaShuma** [comment]
敵との当たり判定をコライダーではなくターゲットとの距離にしました。
現状直書きで距離を設定しているけど、今後、スキルデータから持ってこれるようにしたい
